# uso do pandas para a manipulação de planilha e CSVs
### normalmente usamos  essa estrutura:

-> leitura dos arquivos com ´´´python pd.read_tpfile('nome do arquivo', argumentos necessários referentes ao aarquivo)´´´
e sua printagem com a função display(disponivel no jupyter).

In [2]:
import pandas as pd
import numpy as np

df_pedidos = pd.read_csv('vou_definir.csv', sep = ',')
display(df_pedidos.head())

df_pedidos01 = pd.read_excel('tabela_test_pandas_python.xlsx')
#display(df_pedidos01.tail(),start = df_pedidos01[4:5])


# exibir a partir do índice desejado (ex: a partir do índice 5)
display(df_pedidos01.loc[5:])

,DATA DE ATUALIZAÇÃO,NÚMERO RASTREIO,ENTREGADOR,DATA DO PEDIDO,DATA DA ENTREGA,R$ PEDIDO
0,01/01/2026,FEB 888 315 00,João Paulo,01/01/2026,10/01/2026,5123
1,08/01/2026,BEA 690 513 19,João Paulo,08/01/2026,18/01/2026,100
2,15/01/2026,CAF 357 535 56,Fabio Alves,15/01/2026,25/01/2026,621
3,22/01/2026,CAC 575 866 31,Natalia Silva,22/01/2026,01/02/2026,748
4,29/01/2026,DFD 917 431 29,João Paulo,29/01/2026,08/02/2026,537

,DATA DE ATUALIZAÇÃO,NÚMERO RASTREIO,ENTREGADOR,DATA DO PEDIDO,DATA DA ENTREGA,R$ PEDIDO
5,2026-02-05,ADB 333 371 07,João Paulo,2026-02-05,2026-02-15,355
6,2026-02-12,FCE 591 943 15,Fabio Alves,2026-02-12,2026-02-22,123
7,2026-02-19,FFF 978 351 54,Natalia Silva,2026-02-19,2026-03-01,554
8,2026-02-26,CEB 700 405 32,Natalia Silva,2026-02-26,2026-03-08,745

  usei a indexação para definir quais linhas apereciam no protocolo tail e head

# uso do pandas para manipulação de jsons e dicts

### estrutura:

normalmente estrutura para a manipulação dos arqiuvos json, funciona a base de leitura e depois escrita, usando os parametros:
- nome do arquivo
- 'r', 'w' e etc (read and write)
- encouding = "utf-8", para evitar problemas envolvendo acentuações
- tratamento de onjetos, desancapsulamento de objetos internos,(já que colunas não possuem sub - colunas)

In [1]:
import pandas as pd


pedidos = {
    'id': [1, 2, 3],
    'cliente': ['João', 'Maria', 'Pedro'],
    'tp_produto': ['A', 'B', 'C'],
    'valor': [100.0, 200.0, 305.0],
    'qtde' : [5,8,20],      
    'resultado' : ['Aprovado', 'Reprovado', 'Aprovado'],
    'problemas encontrados' : ['Nenhum', 'Falta de estoque', 'Nenhum'],
    'status_entrega' : ['Entregue', 'Pendente', 'Entregue'],
    'dia da entrega' : ['2023-06-01', '2023-06-05', '2023-06-10']
    }
df1= pd.DataFrame(pedidos)

display(df1)

,id,cliente,tp_produto,valor,qtde,resultado,problemas encontrados,status_entrega,dia da entrega
0,1,João,A,100.0,5,Aprovado,Nenhum,Entregue,2023-06-01
1,2,Maria,B,200.0,8,Reprovado,Falta de estoque,Pendente,2023-06-05
2,3,Pedro,C,305.0,20,Aprovado,Nenhum,Entregue,2023-06-10